const verses = [
  "About what do they question one another?",
  "about the Great Tiding,",
  "regarding which they differ.",
  "Nay, but they will know!",
  "Then indeed they will know!",
  "Did We not make the earth a resting place,",
  "and the mountains stakes,",
  "and create you in pairs,",
  "and make your sleep repose,",
  "and make the night a garment,",
  "and the day for livelihood?",
  "And [did We not] build above you seven firmaments,",
  "and make a radiant lamp,",
  "and send down water pouring from the rain clouds,",
  "that We might produce grain and plants thereby,",
  "and luxuriant gardens?",
  "Truly the Day of Division is a Moment Appointed,",
  "a day when the trumpet is blown and you come forth in throngs,",
  "and the sky is opened as if it were gates,",
  "and the mountains are set in motion as if they were a mirage.",
  "Truly Hell lies in ambush,",
  "a place unto which the rebellious return",
  "to tarry therein for ages.",
  "They taste therein neither coolness nor drink,",
  "save boiling liquid and a cold, murky fluid,",
  "a fitting recompense.",
  "Truly they anticipated not a reckoning,",
  "and denied Our signs with utter denial.",
  "And everything have We recorded in a book.",
  "So taste! For We shall not increase you in aught but punishment!",
  "Truly the reverent shall have a place of triumph,",
  "gardens and vineyards,",
  "buxom maidens of like age,",
  "and an overflowing cup.",
  "They hear therein neither idle talk nor lying--",
  "a recompense from thy Lord, a gift abounding--",
  "the Lord of the heavens and the earth, and whatsoever is between them, the Compassionate, Whom they have no power to address.",
  "That Day the Spirit and the angels stand in rows, none speaking, save one whom the Compassionate permits and who speaks aright.",
  "That is the True Day. So let whosoever will, take a path of return unto his Lord.",
  "Truly We have warned you of a punishment nigh, on a day when a man beholds what his hands have sent forth, and the disbeliever says, \"Oh, would that I were dust!\""
]

const commentary = [
  "Here, \"They\" could refer to the people in Muhammad's tribe, many of whom were disbelievers. It could also be a reference to all disbelievers who are questioning the teachings.",
  "\"The Great Tiding\" could refer to one or more of three possibilities: the Qur'an itself, Muhammad, or the Resurrection. In this context, the Resurrection seems most likely. This is the day where all humans will be raised from their graves to be judged in front of God.",
  "Disbelievers have different opinions both on the Resurrection and on the Qur'an itself. Some of them believe in the Resurrection, while others don't. In addition, some believe in the validity of the Qur'an, while others question its roots and whether the verses are truly revelations from God.",
  "See verse 5.",
  "It is unclear what the intended audience of verses 4 and 5 are. Perhaps they are both meant for disbelievers, and the repetition serves to emphasize the misery they will soon know, once the day arrives. Or, it could be that the first verse is meant for disbelievers, and the second is meant for believers, who will soon know their reward.",
  "See verse 8,",
  "See verse 8,",
  "Verse 6-8 bear witness to everything God has provided for humankind. He has made the earth a good and restful place, and a perfect home. The mountains serve as a place of refuge and provide natural resources. Humans were created in male and female pairs so that we could reproduce and keep one another company.",
  "God gave us sleep to replenish our energy during the night, and have a break for the hardships of life.",
  "The night serves as protection for humans. In addition, the stillness and calmness of night allows for proper devotion and worship.",
  "This verse contrasts with the two previous verse which discuss the importance of the night and of rest. The daytime is for life, vigor, and action. Rest during the night serves to give us the energy to carry out our deeds during the day. There are many references in the Qur'an to the importance of this cycle of rest and activity, which is essential to human life.",
  "The seven firmaments refer to the seven major planets in the solar system. It shows how God created a perfect, flawless, complex system in which humans play a key role.",
  "The lamp in this context refers to the sun, which was created by God to bring life to our planet.",
  "Like the sun, water is essential for human life. These verses serve to reinforce the fact that God provided everything humans need.",
  "See verse 16.",
  "Grains, plants, and gardens represent life and vitality. The notion of the garden is an important religious symbol that speaks directly to the power and the goodness of God.",
  "The Day of Division also refers to the Day of Resurrection. It is the day where truth will triumph over evil, and where believers and nonbelievers alike will see the punishments and rewards of their actions.",
  "When the trumpet is blown, all humankind will come before God to be judged.",
  "See verse 20.",
  "Verse 19 and 20 give a physical representation of the power of the day of Resurrection. Things previously thought to be solid and unbreakable, such as the sky and the mountains, will be easily cast aside to allow the angels to come down onto the Earth, and for humans to be lifted from their graves and brought to their respective fates.",
  "See verse 22.",
  "Hell awaits those who do not believe and do not do good deeds. Since disbelievers do not believe they will go to Hell, it waits in ambush for those who deserve it.",
  "There is some disagreement about how long one would spend in hell. While some believe Hell is eteneral, others interpret \"ages\" to be a long, yet finite amount of time, contrasting with the explicit eternity of Heaven.",
  "See verse 25.",
  "In Hell, the only things available to drink are unbearably hot or cold. A common theme in the Qur'an, this shows how torture and pain are found at the extremes, while pleasure is found in moderation.",
  "Those who end up in Hell deserve the fate that they received.",
  "Disbelievers did not believe in this day of reckoning, and never expected to be sent to Hell.",
  "The signs refered to in this verse represent the clear evidence all around of the power and goodness of God. And yet, disbelievers still were not convinced.",
  "God and the angels have recorded all the actions of humans in a divine book, which is opened and examined on this day to determine each individual's fate.",
  "This is a very strong warning towards disbelievers, telling them that God will continually increase their punishment, and that they will have to taste the consequences of their deeds. The only thing they will see in the future is punishment.",
  "See verse 32.",
  "On the other hand, believers will bathe in everlasting bliss. The reference to gardens and nature is once again used to represent Heaven.",
  "Those who enter paradise will be youthful, and the same age as all others around.",
  "The cup is a reference to heavenly wine, which will be enjoyed by believers who enter Heaven. Unlike Hell, Heaven is a land of plenty.",
  "Idle talk and lying, which are traits of disbelievers, do not exist in Heaven. Instead, only words of joy and worship will be heard.",
  "All of this is a reward for God for believing in Him and doing good.",
  "This verse affirms God as the Lord of the entire universe. \"They\" could be referring to disbelievers, who will not be allowed to address God directly.",
  "On the Day of Resurrection, all the angels and the Spirit will come before God, silent. The Spirit could refer to the Archangel Gabriel, or perhaps the Holy Prophet. It is said that God will choose someone to intercede on behalf of the others, and he alone will be allowed to speak.",
  "God welcomes all believers. Anybody who wishes to reap the rewards of Heaven need only follow the path of God."
]

export { verses, commentary }
